name: Deploy to GitHub Pages
on:
  push:
    branches: [ master ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Create config.js
        run: |
          echo "window.WEATHER_API_KEY = '${{ secrets.OPENWEATHER_API_KEY }}';
          window.STREETVIEW_API_KEY = '${{ secrets.GOOGLE_STREETVIEW_API_KEY }}';" > config.js
          
      - name: Update index.html
        run: |
          sed -i 's/config\.OPENWEATHER_API_KEY/window.WEATHER_API_KEY/g' index.html
          sed -i 's/config\.GOOGLE_STREETVIEW_API_KEY/window.STREETVIEW_API_KEY/g' index.html
          
      - name: Debug files
        run: |
          echo "Config.js contents (masked):"
          sed 's/[A-Za-z0-9]\{20,\}/***MASKED***/g' config.js
          echo "Index.html API references:"
          grep -o "window\.[A-Z_]*" index.html || true
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 