name: Deploy to GitHub Pages
on:
  push:
    branches: [ master ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Create replace script
        run: |
          echo "const fs = require('fs');
          const html = fs.readFileSync('index.html', 'utf8');
          const replaced = html
            .replace(/OPENWEATHER_API_KEY_HERE/g, process.env.OPENWEATHER_API_KEY)
            .replace(/STREETVIEW_API_KEY_HERE/g, process.env.STREETVIEW_API_KEY);
          fs.writeFileSync('index.html', replaced);
          console.log('Replacements complete');" > replace.js
          
      - name: Inject secrets
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          STREETVIEW_API_KEY: ${{ secrets.GOOGLE_STREETVIEW_API_KEY }}
        run: node replace.js
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 